/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109585-g379e43e6ec-20230111"
#endif /* AVUTIL_FFVERSION_H */
